// Mock Data Store for Users
export const mockUsers = [
  // ROOKIE x4
  {
    id: 'user-1',
    name: 'Nisa Ops',
    email: 'nisa@rnkd.com',
    phone: '+6281234567893',
    avatar_url: null,
    province: 'Jakarta',
    city: 'Central Jakarta',
    role: 'user' as const,
    created_at: '2025-01-10T00:00:00Z',
    profile: {
      mmr: 850,
      tier: 'ROOKIE' as const,
      pbpi_grading: 'D',
      matches_played: 2,
      wins: 0,
      losses: 2,
      win_rate: 0,
    },
  },
  {
    id: 'user-2',
    name: 'Ari Drop',
    email: 'ari.drop@gmail.com',
    phone: '+6281234567900',
    avatar_url: null,
    province: 'Bali',
    city: 'Gianyar',
    role: 'user' as const,
    created_at: '2025-03-15T00:00:00Z',
    profile: {
      mmr: 780,
      tier: 'ROOKIE' as const,
      pbpi_grading: 'D',
      matches_played: 3,
      wins: 1,
      losses: 2,
      win_rate: 33.3,
    },
  },
  {
    id: 'user-3',
    name: 'Budi Lob',
    email: 'budi.lob@gmail.com',
    phone: '+6281234567901',
    avatar_url: null,
    province: 'Jakarta',
    city: 'East Jakarta',
    role: 'user' as const,
    created_at: '2025-04-02T00:00:00Z',
    profile: {
      mmr: 820,
      tier: 'ROOKIE' as const,
      pbpi_grading: 'D',
      matches_played: 4,
      wins: 1,
      losses: 3,
      win_rate: 25.0,
    },
  },
  {
    id: 'user-4',
    name: 'Citra Spin',
    email: 'citra.spin@gmail.com',
    phone: '+6281234567902',
    avatar_url: null,
    province: 'Bali',
    city: 'Denpasar',
    role: 'user' as const,
    created_at: '2025-05-20T00:00:00Z',
    profile: {
      mmr: 900,
      tier: 'ROOKIE' as const,
      pbpi_grading: 'D+',
      matches_played: 5,
      wins: 2,
      losses: 3,
      win_rate: 40.0,
    },
  },
  // CHALLENGER x4
  {
    id: 'user-5',
    name: 'Wayan Tech',
    email: 'wayan@rnkd.com',
    phone: '+6281234567892',
    avatar_url: null,
    province: 'Bali',
    city: 'Badung',
    role: 'admin' as const,
    created_at: '2025-01-05T00:00:00Z',
    profile: {
      mmr: 1050,
      tier: 'CHALLENGER' as const,
      pbpi_grading: 'C',
      matches_played: 8,
      wins: 3,
      losses: 5,
      win_rate: 37.5,
    },
  },
  {
    id: 'user-6',
    name: 'Dewa Power',
    email: 'dewa.power@gmail.com',
    phone: '+6281234567903',
    avatar_url: null,
    province: 'Jakarta',
    city: 'South Jakarta',
    role: 'user' as const,
    created_at: '2025-02-14T00:00:00Z',
    profile: {
      mmr: 1080,
      tier: 'CHALLENGER' as const,
      pbpi_grading: 'C',
      matches_played: 10,
      wins: 5,
      losses: 5,
      win_rate: 50.0,
    },
  },
  {
    id: 'user-7',
    name: 'Eka Slice',
    email: 'eka.slice@gmail.com',
    phone: '+6281234567904',
    avatar_url: null,
    province: 'Bali',
    city: 'Seminyak',
    role: 'user' as const,
    created_at: '2025-03-01T00:00:00Z',
    profile: {
      mmr: 1020,
      tier: 'CHALLENGER' as const,
      pbpi_grading: 'C-',
      matches_played: 7,
      wins: 3,
      losses: 4,
      win_rate: 42.9,
    },
  },
  {
    id: 'user-8',
    name: 'Fajar Drive',
    email: 'fajar.drive@gmail.com',
    phone: '+6281234567905',
    avatar_url: null,
    province: 'Jakarta',
    city: 'West Jakarta',
    role: 'user' as const,
    created_at: '2025-04-12T00:00:00Z',
    profile: {
      mmr: 1110,
      tier: 'CHALLENGER' as const,
      pbpi_grading: 'C+',
      matches_played: 12,
      wins: 7,
      losses: 5,
      win_rate: 58.3,
    },
  },
  // CONTENDER x4
  {
    id: 'user-9',
    name: 'Bobby CPO',
    email: 'bobby@rnkd.com',
    phone: '+6281234567891',
    avatar_url: null,
    province: 'Jakarta',
    city: 'South Jakarta',
    role: 'admin' as const,
    created_at: '2025-01-02T00:00:00Z',
    profile: {
      mmr: 1320,
      tier: 'CONTENDER' as const,
      pbpi_grading: 'B',
      matches_played: 22,
      wins: 12,
      losses: 10,
      win_rate: 54.5,
    },
  },
  {
    id: 'user-10',
    name: 'Gita Ace',
    email: 'gita.ace@gmail.com',
    phone: '+6281234567906',
    avatar_url: null,
    province: 'Bali',
    city: 'Canggu',
    role: 'user' as const,
    created_at: '2025-02-20T00:00:00Z',
    profile: {
      mmr: 1280,
      tier: 'CONTENDER' as const,
      pbpi_grading: 'B-',
      matches_played: 18,
      wins: 9,
      losses: 9,
      win_rate: 50.0,
    },
  },
  {
    id: 'user-11',
    name: 'Hendra Chop',
    email: 'hendra.chop@gmail.com',
    phone: '+6281234567907',
    avatar_url: null,
    province: 'Jakarta',
    city: 'North Jakarta',
    role: 'user' as const,
    created_at: '2025-03-10T00:00:00Z',
    profile: {
      mmr: 1350,
      tier: 'CONTENDER' as const,
      pbpi_grading: 'B',
      matches_played: 20,
      wins: 12,
      losses: 8,
      win_rate: 60.0,
    },
  },
  {
    id: 'user-12',
    name: 'Indra Wall',
    email: 'indra.wall@gmail.com',
    phone: '+6281234567908',
    avatar_url: null,
    province: 'Bali',
    city: 'Sanur',
    role: 'user' as const,
    created_at: '2025-04-05T00:00:00Z',
    profile: {
      mmr: 1240,
      tier: 'CONTENDER' as const,
      pbpi_grading: 'B-',
      matches_played: 15,
      wins: 7,
      losses: 8,
      win_rate: 46.7,
    },
  },
  // ELITE x4
  {
    id: 'user-13',
    name: 'Steven CEO',
    email: 'steven@rnkd.com',
    phone: '+6281234567890',
    avatar_url: null,
    province: 'Bali',
    city: 'Denpasar',
    role: 'admin' as const,
    created_at: '2025-01-01T00:00:00Z',
    profile: {
      mmr: 1542,
      tier: 'ELITE' as const,
      pbpi_grading: 'A',
      matches_played: 14,
      wins: 10,
      losses: 4,
      win_rate: 71.4,
    },
  },
  {
    id: 'user-14',
    name: 'Joko Flat',
    email: 'joko.flat@gmail.com',
    phone: '+6281234567909',
    avatar_url: null,
    province: 'Jakarta',
    city: 'South Jakarta',
    role: 'user' as const,
    created_at: '2025-01-20T00:00:00Z',
    profile: {
      mmr: 1480,
      tier: 'ELITE' as const,
      pbpi_grading: 'A-',
      matches_played: 30,
      wins: 20,
      losses: 10,
      win_rate: 66.7,
    },
  },
  {
    id: 'user-15',
    name: 'Kadek Smash',
    email: 'kadek.smash@gmail.com',
    phone: '+6281234567910',
    avatar_url: null,
    province: 'Bali',
    city: 'Ubud',
    role: 'user' as const,
    created_at: '2025-02-05T00:00:00Z',
    profile: {
      mmr: 1520,
      tier: 'ELITE' as const,
      pbpi_grading: 'A',
      matches_played: 28,
      wins: 19,
      losses: 9,
      win_rate: 67.9,
    },
  },
  {
    id: 'user-16',
    name: 'Made Volley',
    email: 'made.volley@gmail.com',
    phone: '+6281234567911',
    avatar_url: null,
    province: 'Bali',
    city: 'Kuta',
    role: 'user' as const,
    created_at: '2025-03-18T00:00:00Z',
    profile: {
      mmr: 1460,
      tier: 'ELITE' as const,
      pbpi_grading: 'A-',
      matches_played: 25,
      wins: 16,
      losses: 9,
      win_rate: 64.0,
    },
  },
  // MASTERS x3
  {
    id: 'user-17',
    name: 'Agus Padel',
    email: 'agus@gmail.com',
    phone: '+6281234567894',
    avatar_url: null,
    province: 'Bali',
    city: 'Gianyar',
    role: 'user' as const,
    created_at: '2025-02-01T00:00:00Z',
    profile: {
      mmr: 1850,
      tier: 'MASTERS' as const,
      pbpi_grading: 'A+',
      matches_played: 45,
      wins: 38,
      losses: 7,
      win_rate: 84.4,
    },
  },
  {
    id: 'user-18',
    name: 'Putu Rally',
    email: 'putu.rally@gmail.com',
    phone: '+6281234567912',
    avatar_url: null,
    province: 'Bali',
    city: 'Denpasar',
    role: 'user' as const,
    created_at: '2025-01-15T00:00:00Z',
    profile: {
      mmr: 1780,
      tier: 'MASTERS' as const,
      pbpi_grading: 'A+',
      matches_played: 40,
      wins: 32,
      losses: 8,
      win_rate: 80.0,
    },
  },
  {
    id: 'user-19',
    name: 'Komang Net',
    email: 'komang.net@gmail.com',
    phone: '+6281234567913',
    avatar_url: null,
    province: 'Bali',
    city: 'Tabanan',
    role: 'user' as const,
    created_at: '2025-02-28T00:00:00Z',
    profile: {
      mmr: 1720,
      tier: 'MASTERS' as const,
      pbpi_grading: 'A',
      matches_played: 35,
      wins: 27,
      losses: 8,
      win_rate: 77.1,
    },
  },
  // ICONS x1
  {
    id: 'user-20',
    name: 'Gede Serve',
    email: 'gede.serve@gmail.com',
    phone: '+6281234567914',
    avatar_url: null,
    province: 'Bali',
    city: 'Denpasar',
    role: 'user' as const,
    created_at: '2025-01-01T00:00:00Z',
    profile: {
      mmr: 2150,
      tier: 'ICONS' as const,
      pbpi_grading: 'S',
      matches_played: 62,
      wins: 55,
      losses: 7,
      win_rate: 88.7,
    },
  },
];

export const mockDashboardStats = {
  totalUsers: 1245,
  userTrend: 12,
  matchesThisWeek: 84,
  matchesTrend: 8,
  pendingVerifications: 5,
  activeDisputes: 2,
  averageMMR: 1087,
  mmrTrend: 3,
  activeSeasons: 2,
  totalClubs: 24,
};
